---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: always
  image: spritsail/docker-build
  settings:
    repo: sonarr-beta-dev

- name: test
  pull: always
  image: spritsail/docker-test
  settings:
    curl: :8989/api/system/status
    curl_opts: --header x-api-key:drone
    pipe: |
      jq -r ".version" |
      grep -qw "$(label io.spritsail.version.sonarr)"
    repo: sonarr-beta-dev
    run_args: -t -e SUID=0 -e API_KEY=drone
    verbose: true

- name: publish
  pull: always
  image: spritsail/docker-publish
  settings:
    from: sonarr-beta-dev
    repo: spritsail/sonarr
    tags:
    - beta
    - "%label io.spritsail.version.sonarr | %prefix beta | %auto"
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch:
    - beta
    event:
    - push

---
kind: signature
hmac: 25e3095244e47296eee1a7d7f3149c4600c13d606c17220b7d785c36725c6a5c

...
